### ISSUE TITLE
TODO Implementations

### ISSUE THREAD

**Issue by Kraks** [Kraks/sai#3]
Core language:
- [x] Core language parser - @yuxuanchen1997 
- [x] Core language concrete interpreters (small-step, refunc., big-step) - @Kraks
- [x] Core language abstract interpreters (AAM, ADI, path/flow/context-sensitive, store-widening, abstract domains) - @Kraks
- [x] Core language staged abstract interpreters

Large language:
- [x] Benchmarks
- [x] Large language parser - @yuxuanchen1997
- [x] Large language concrete interpreters - @yuxuanchen1997
- [x] Large language abstract interpreters (small-step and big-step, as baselines)
- [x] Large language staged abstract interpreters

For comparisons (on the benchmarks):
- [ ] Small-step AAM with abstract compilation (ICFP13)
- [ ] Fully optimized AAM (ICFP13)
- [ ] ADI with abstract compilation
